name: mole-ai

channels:
  - conda-forge

dependencies:
  - python=3.11
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - streamlit==1.59.2
      - plotly==6.9.0
