name: mole-ai

channels:
  - conda-forge
  - pytorch

dependencies:
  - python=3.11
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - jupyter
  - pytorch
  - pip
  - pip:
      - plotly==6.3.0
      - deepchem
      - pytest
      - black
      - ruff
