"""
MOLE-AI v2 Molecular Library Intelligence.

Analyzes batch screening results and identifies
the strongest candidates in a molecular library.
"""

import pandas as pd


class LibraryAnalyzer:
    """
    Analyze and summarize a batch molecular screening library.
    """

    def analyze(self, results: pd.DataFrame) -> dict:
        """
        Analyze batch screening results.

        Parameters
        ----------
        results : pandas.DataFrame
            Results generated by BatchScreeningWorkflow.

        Returns
        -------
        dict
            Library-level screening insights.
        """

        if results is None or results.empty:
            raise ValueError(
                "Screening results are empty."
            )

        required_columns = [
            "SMILES",
            "Predicted pIC50",
            "Activity",
            "ADMET Score",
            "Overall Score",
            "Priority",
            "Status",
        ]

        missing_columns = [
            column
            for column in required_columns
            if column not in results.columns
        ]

        if missing_columns:
            raise ValueError(
                "Missing required columns: "
                + ", ".join(missing_columns)
            )

        # Work on a copy so the original DataFrame
        # is never modified.
        dataframe = results.copy()

        # --------------------------------------------------
        # Numeric conversion
        # --------------------------------------------------

        dataframe["Predicted pIC50"] = pd.to_numeric(
            dataframe["Predicted pIC50"],
            errors="coerce",
        )

        dataframe["ADMET Score"] = pd.to_numeric(
            dataframe["ADMET Score"],
            errors="coerce",
        )

        dataframe["Overall Score"] = pd.to_numeric(
            dataframe["Overall Score"],
            errors="coerce",
        )

        # Keep successfully analyzed molecules.
        successful = dataframe[
            dataframe["Status"] == "Success"
        ].copy()

        if successful.empty:
            raise ValueError(
                "No successfully analyzed molecules found."
            )

        # --------------------------------------------------
        # Top candidate
        # --------------------------------------------------

        top_candidate = successful.loc[
            successful["Overall Score"].idxmax()
        ]

        # --------------------------------------------------
        # Best activity candidate
        # --------------------------------------------------

        best_activity = successful.loc[
            successful["Predicted pIC50"].idxmax()
        ]

        # --------------------------------------------------
        # Best ADMET candidate
        # --------------------------------------------------

        best_admet = successful.loc[
            successful["ADMET Score"].idxmax()
        ]

        # --------------------------------------------------
        # Priority counts
        # --------------------------------------------------

        priority_counts = (
            successful["Priority"]
            .value_counts()
            .to_dict()
        )

        high_priority = int(
            priority_counts.get(
                "High Priority",
                0,
            )
        )

        medium_priority = int(
            priority_counts.get(
                "Medium Priority",
                0,
            )
        )

        low_priority = int(
            priority_counts.get(
                "Low Priority",
                0,
            )
        )

        # --------------------------------------------------
        # Screening statistics
        # --------------------------------------------------

        total_molecules = len(dataframe)

        successful_molecules = len(successful)

        failed_molecules = (
            total_molecules
            - successful_molecules
        )

        success_rate = (
            successful_molecules
            / total_molecules
            * 100
        )

        average_pic50 = successful[
            "Predicted pIC50"
        ].mean()

        average_admet = successful[
            "ADMET Score"
        ].mean()

        average_overall = successful[
            "Overall Score"
        ].mean()

        # --------------------------------------------------
        # Top 5 candidates
        # --------------------------------------------------

        top_candidates = (
            successful
            .sort_values(
                by="Overall Score",
                ascending=False,
            )
            .head(5)
            .reset_index(drop=True)
        )

        # Add ranking.
        top_candidates.insert(
            0,
            "Library Rank",
            range(
                1,
                len(top_candidates) + 1,
            ),
        )

        # --------------------------------------------------
        # Candidate recommendation
        # --------------------------------------------------

        top_score = float(
            top_candidate["Overall Score"]
        )

        if top_score >= 80:

            recommendation = (
                "Strong library candidate. "
                "Prioritize for downstream computational "
                "validation."
            )

        elif top_score >= 60:

            recommendation = (
                "Promising library candidate. "
                "Consider further optimization and "
                "computational validation."
            )

        else:

            recommendation = (
                "No strongly prioritized candidates were "
                "identified. Consider molecular optimization."
            )

        # --------------------------------------------------
        # Return library intelligence
        # --------------------------------------------------

        return {
            "total_molecules": int(
                total_molecules
            ),

            "successful_molecules": int(
                successful_molecules
            ),

            "failed_molecules": int(
                failed_molecules
            ),

            "success_rate": round(
                float(success_rate),
                2,
            ),

            "average_predicted_pIC50": round(
                float(average_pic50),
                3,
            ),

            "average_admet_score": round(
                float(average_admet),
                2,
            ),

            "average_overall_score": round(
                float(average_overall),
                2,
            ),

            "high_priority_count": high_priority,

            "medium_priority_count": medium_priority,

            "low_priority_count": low_priority,

            "top_candidate": {
                "smiles": top_candidate["SMILES"],
                "predicted_pIC50": float(
                    top_candidate["Predicted pIC50"]
                ),
                "activity": top_candidate[
                    "Activity"
                ],
                "admet_score": float(
                    top_candidate["ADMET Score"]
                ),
                "overall_score": float(
                    top_candidate["Overall Score"]
                ),
                "priority": top_candidate[
                    "Priority"
                ],
            },

            "best_activity_candidate": {
                "smiles": best_activity["SMILES"],
                "predicted_pIC50": float(
                    best_activity["Predicted pIC50"]
                ),
                "activity": best_activity[
                    "Activity"
                ],
            },

            "best_admet_candidate": {
                "smiles": best_admet["SMILES"],
                "admet_score": float(
                    best_admet["ADMET Score"]
                ),
                "priority": best_admet[
                    "Priority"
                ],
            },

            "top_candidates": top_candidates,

            "recommendation": recommendation,
        }
